'use strict';

module.exports = {

    addBooking: require('./addBooking'),
    addFine: require('./addFine'),
    addLibBook: require('./addLibBook'),
    addLibrarian: require('./addLibrarian'),
    addLibraryUser: require('./addLibraryUser'),
    createLibrary: require('./createLibrary'),
    deleteBooking: require('./deleteBooking'),
    deleteLibFine: require('./deleteLibFine'),
    deleteLibraryById: require('./deleteLibraryById'),
    deleteLibraryUser: require('./deleteLibraryUser'),
    getAllBookingsSortable: require('./getAllBookingsSortable'),
    getAllFines: require('./getAllFines'),
    getAllFinesSortable: require('./getAllFinesSortable'),
    getAllLibraries: require('./getAllLibraries'),
    getAllLibraryVisitsSortable: require('./getAllLibraryVisitsSortable'),
    getAllLibrariesSortable: require('./getAllLibrariesSortable'),
    getAllNotReturnedReadings: require('./getAllNotReturnedReadings'),
    getAllReadings: require('./getAllReadings'),
    getAllReadingsSortable: require('./getAllReadingsSortable'),
    getBookingsBookInLibrary: require('./getBookingsBookInLibrary'),
    getBookingsByUser: require('./getBookingsByUser'),
    getBookingCountBook: require('./getBookingCountBook'),
    getBookingCountLibrary: require('./getBookingCountLibrary'),
    getFineById: require('./getFineById'),
    getFinesByUser: require('./getFinesByUser'),
    getLibBook: require('./getLibBook'),
    getLibBooksByBook: require('./getLibBooksByBook'),
    getLibBookById: require('./getLibBookById'),
    getLibBookBySection: require('./getLibBookBySection'),
    getLibFineCountLibrary: require('./getLibFineCountLibrary'),
    getLibraryBooksById: require('./getLibraryBooksById'),
    getLibraryBooksByIdSortable: require('./getLibraryBooksByIdSortable'),
    getLibraryBooksCount: require('./getLibraryBooksCount'),
    getLibraryById: require('./getLibraryById'),
    getLibraryCount: require('./getLibraryCount'),
    getLibraryIDByOwner: require('./getLibraryIDByOwner'),
    getLibraryUsersById: require('./getLibraryUsersById'),
    getLibraryUsersCount: require('./getLibraryUsersCount'),
    getLibraryUsersInLibraryCount: require('./getLibraryUsersInLibraryCount'),
    getUserBookingsAndReadings: require('./getUserBookingsAndReadings'),
    getUserLibraryVisits: require('./getUserLibraryVisits'),
    getUserPendingReadings: require('./getUserPendingReadings'),
    getReadingCountLibrary: require('./getReadingCountLibrary'),
    importBooks: require('./importBooks'),
    isBookAvailable: require('./isBookAvailable'),
    isMember: require('./isMember'),
    returnBook: require('./returnBook'),
    takeBook: require('./takeBook'),
    updateLibBook: require('./updateLibBook'),
    updateLibrary: require('./updateLibrary'),
    libraryNameAvailable: require('./libraryNameAvailable')

};